printWidth: 120
trailingComma: es5
tabWidth: 2
semi: false
singleQuote: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - '^react$'
  - '^react-dom$'
  - '^next'
  - '<THIRD_PARTY_MODULES>'
  - '^@/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
